// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6G1RfrrpDfQNO0tJ_7gcZV5TOf8rMfg',
    appId: '1:1054933453473:android:4cea8a17099f4509247ee0',
    messagingSenderId: '1054933453473',
    projectId: 'docflow-959dc',
    storageBucket: 'docflow-959dc.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNYxnYT3TIeWx90tzzAJXFcW2gWA7Ea_g',
    appId: '1:1054933453473:web:adbca23d7fb45610247ee0',
    messagingSenderId: '1054933453473',
    projectId: 'docflow-959dc',
    authDomain: 'docflow-959dc.firebaseapp.com',
    storageBucket: 'docflow-959dc.firebasestorage.app',
    measurementId: 'G-NHQBJWS23S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1aH9Fpbktnn9qcrqSC29jMsKh4y_Swo',
    appId: '1:1054933453473:ios:4e1868e23280f6bd247ee0',
    messagingSenderId: '1054933453473',
    projectId: 'docflow-959dc',
    storageBucket: 'docflow-959dc.firebasestorage.app',
    iosClientId: '1054933453473-jrr3p8va4rr9kg4cibkehuimvigu5mcg.apps.googleusercontent.com',
    iosBundleId: 'com.weversity.docflow',
  );
}
